docs: update existing PR comments example
hashicorp/setup-terraform pull request #178
Opened 2022-04-06 15:14 UTC by tobiasbueschel

Thanks for all your efforts with this github action 👏

This PR improves the example in the documentation by ensuring that the PR comment made is updated instead of creating a new comment. I realize that in some situations a new comment is desirable, however, this PR assumes that for most use cases updating an existing comment for a PR is desirable.

2022-04-06 15:14 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/setup-terraform?pullRequest=178)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/setup-terraform?pullRequest=178)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/setup-terraform?pullRequest=178).</sub>

2022-04-07 14:11 UTC, jpogran requested changes
Thank you @tobiasbueschel for the contribution! I do think this is a valuable example to add, but also think it is valuable to have the prior example in addition to this one.

Can you leave the current example as is, and make your example an entirely new one underneath this? This way we take the explanation you put in the PR description inside the README and users can see the different ways you can configure this action.

2022-04-08 01:15 UTC, tobiasbueschel commented
@jpogran absolutely, I've just updated the PR to reflect this :) Do let me know if there's anything else I should change. Thanks

2022-04-08 12:19 UTC, jpogran approved these changes

2022-04-08 12:24 UTC, merged