Add new-style readme build badges and table of contents
hashicorp/setup-terraform pull request #188
Opened 2022-04-29 03:26 UTC by magnetikonline

Some quality of life things in `README.md`:

- Using the "new style" build/workflow buttons, which also links better to the action run logs under the actions tab.
- Added TOC to `README.md` generated with (self plug!) https://magnetikonline.github.io/markdown-toc-generate/
- Some whitespace clean up.

2022-05-18 12:57 UTC, jpogran requested changes
Thank you for the help with the documentation. This looks great with the exception of the TOC. Your project looks very useful in other contexts, but HashiCorp follows a general format for a README and we don't include a TOC in most cases. This README isn't long enough to warrant one and GitHub already creates anchors for all of the headers to link to.

2022-05-19 07:13 UTC, magnetikonline commented
No dramas @jpogran - have rebased and removed be5405d.

2022-05-20 14:08 UTC, jpogran approved these changes

2022-09-16 16:01 UTC, jpogran approved these changes

2022-09-16 16:01 UTC, merged