Fixed `master` to `main` workflow branch triggers
hashicorp/setup-terraform pull request #216
Opened 2022-06-14 00:20 UTC by magnetikonline

- Noted this project has now been moved from `master` to `main` as the mainline branch (yay!)
- ...but found a few places where things still reference `master`. The GitHub workflows being the most pressing (as they are not currently running in these states).
- Also removed a bit of YAML quoting that's not needed in strings.

2022-06-14 00:20 UTC, magnetikonline commented on .github/workflows/continuous-integration.yml
> +    - main
Important change.

2022-06-14 00:20 UTC, magnetikonline commented on .github/workflows/setup-terraform.yml
> +    - main
Important change.

2022-06-14 00:21 UTC, magnetikonline commented on README.md
> +[Mozilla Public License v2.0](LICENSE)
No need to give an absolute URL to these documents - fixes the branch reference issue.

2022-06-14 00:21 UTC, magnetikonline commented on README.md
> +[Code of Conduct](CODE_OF_CONDUCT.md)
No need to give an absolute URL to these documents - fixes the branch reference issue.

2022-09-16 15:58 UTC, jpogran requested changes
Thanks for catching the Github Actions branch updates! 

Since that is the purpose of this PR, can you please revert the whitespace and quoting changes? They are not required for this changeset.

2022-09-17 06:55 UTC, magnetikonline commented
Done @jpogran

2022-09-17 21:18 UTC, jpogran approved these changes

2022-09-17 21:18 UTC, merged